## Pandas Library

In [1]:
import numpy as np

In [2]:
import pandas as pd

### Creating series

In [3]:
labels = ['a','b','c','d']
list = ['10','20','30','40']
arr=np.array([10,20,30])
dict ={1:10,2:20,3:30}

In [6]:
pd.Series(list,index=labels)

a    10
b    20
c    30
d    40
dtype: object

In [7]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(dict)

1    10
2    20
3    30
dtype: int64

### Data Frame

In [18]:
data={
    'Name':['ram','sham','kam','ramo'],
    'Age':[20,30,45,55],
    'City':['ynr','kuk','radaur','ambala'],
    'Salary':[30000,40000,5000,600000],
    }

In [19]:
df=pd.DataFrame(data)

In [20]:
df

   Name  Age    City  Salary
0   ram   20     ynr   30000
1  sham   30     kuk   40000
2   kam   45  radaur    5000
3  ramo   55  ambala  600000

In [22]:
data_list=[
    ['ram','sham','kam','ramo'],
    [20,30,45,55],
    ['ynr','kuk','radaur','ambala'],
    [30000,40000,5000,600000]
]

In [23]:
df2=pd.DataFrame(data_list)

In [24]:
df2

       0      1       2       3
0    ram   sham     kam    ramo
1     20     30      45      55
2    ynr    kuk  radaur  ambala
3  30000  40000    5000  600000

In [25]:
columns=['name','age','city','salary']

In [26]:
df2=pd.DataFrame(data_list,columns=columns)

In [27]:
df2

    name    age    city  salary
0    ram   sham     kam    ramo
1     20     30      45      55
2    ynr    kuk  radaur  ambala
3  30000  40000    5000  600000

### Selection and indexing of columns

In [28]:
df2

    name    age    city  salary
0    ram   sham     kam    ramo
1     20     30      45      55
2    ynr    kuk  radaur  ambala
3  30000  40000    5000  600000

In [30]:
df2['name']

0      ram
1       20
2      ynr
3    30000
Name: name, dtype: object

In [31]:
df2[['name','city']]

    name    city
0    ram     kam
1     20      45
2    ynr  radaur
3  30000    5000

### Creating a new columns

In [32]:
df2["designation"]=["doctor","pilot","teacher","engineer"]

In [33]:
df2

    name    age    city  salary designation
0    ram   sham     kam    ramo      doctor
1     20     30      45      55       pilot
2    ynr    kuk  radaur  ambala     teacher
3  30000  40000    5000  600000    engineer

### Remove a columns

In [34]:
df2.drop("designation",axis=1)

    name    age    city  salary
0    ram   sham     kam    ramo
1     20     30      45      55
2    ynr    kuk  radaur  ambala
3  30000  40000    5000  600000

In [35]:
df2

    name    age    city  salary designation
0    ram   sham     kam    ramo      doctor
1     20     30      45      55       pilot
2    ynr    kuk  radaur  ambala     teacher
3  30000  40000    5000  600000    engineer

#### designation not remove to remove permantely use inplace

In [36]:
df2.drop("designation",axis=1,inplace=True)

In [37]:
df2

    name    age    city  salary
0    ram   sham     kam    ramo
1     20     30      45      55
2    ynr    kuk  radaur  ambala
3  30000  40000    5000  600000

In [39]:
df2.drop(["age","salary"],axis=1)

    name    city
0    ram     kam
1     20      45
2    ynr  radaur
3  30000    5000

In [40]:
df.drop(0,axis=0)

   Name  Age    City  Salary
1  sham   30     kuk   40000
2   kam   45  radaur    5000
3  ramo   55  ambala  600000

#### for selscting row use loc

In [41]:
df2.loc[[0,1]]

  name   age city salary
0  ram  sham  kam   ramo
1   20    30   45     55

In [42]:
df2.iloc[[0,3]]

    name    age  city  salary
0    ram   sham   kam    ramo
3  30000  40000  5000  600000

#### selecting subset of rows and columns

### CONDITIONAL SELECTION

In [46]:
df

   Name  Age    City  Salary
0   ram   20     ynr   30000
1  sham   30     kuk   40000
2   kam   45  radaur    5000
3  ramo   55  ambala  600000

In [48]:
df[df["Age"]>30]

   Name  Age    City  Salary
2   kam   45  radaur    5000
3  ramo   55  ambala  600000

In [51]:
df[(df["Age"]>30) & (df["City"]=="radaur")]

  Name  Age    City  Salary
2  kam   45  radaur    5000

### Thanks